// <auto-generated />
using API_RESTful_NetCore.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace API_RESTful_NetCore.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20210216192234_my_model")]
    partial class my_model
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.3")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("API_RESTful_NetCore.Entities.Producto", b =>
                {
                    b.Property<string>("pro_codigo")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("pro_descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("pro_nombre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("pro_precio")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("pro_codigo");

                    b.ToTable("Producto");
                });
#pragma warning restore 612, 618
        }
    }
}
